version: '2'

services:
  conanexiles:
    image: alinmear/docker-conanexiles
    restart: always
    environment:
      - "CONANEXILES_ServerSettings_ServerSettings_AdminPassword=ThanksForThisSmartSolution"
      - "CONANEXILES_Engine_OnlineSubSystemSteam_ServerName='My Cool Server'"
      - "CONANEXILES_Engine_OnlineSubSystemSteam_ServerPassword=MySecret"
    ports:
        - 7787:7787/udp
        - 7788:7788/udp
        - 27025:27025/udp
    volumes:
        - data:/conanexiles

volumes:
    data:
        driver: local
