version: '2'

services:
  conanexiles:
    image: alinmear/docker-conanexiles
    restart: always
    environment:
      - "CONANEXILES_Engine_OnlineSubSystemSteam_ServerName='LaggyGamerz Public'"
    ports:
        - 7787:7787/udp
        - 7788:7788/udp
        - 27025:27025/udp
    volumes:
        - data:/conanexiles

volumes:
    data:
        driver: local
